Use case view Requests and case
michellengnx/csc207-project pull request #54
Opened 2023-12-01 00:08 UTC by ISMAELCHONA04

Finalized use case for viewing requests given a user. The Test passes if the file requestTest.csv is empty excluding the 
header.

2023-12-01 18:36 UTC, michellengnx requested changes
Please exclude` .idea/* `from your commit

2023-12-01 18:42 UTC, michellengnx requested changes

2023-12-01 18:42 UTC, michellengnx commented on Dockerfile
No Dockerfile change

2023-12-01 18:42 UTC, michellengnx commented on csc207-project.iml
No config file change

2023-12-01 18:42 UTC, michellengnx commented on src/pom.xml
Do not change my pom.xml file 😠

2023-12-01 22:16 UTC, izorakayumova requested changes
Very informative commits and your packaging structure looks great except for your one test - can you refactor it to test/java/data_access. Please include javadoc for everything that is publicly documented.

2023-12-02 05:21 UTC, michellengnx commented
I am not merging this pull request until all of my comments are resolved.

2023-12-02 16:11 UTC, michellengnx commented
Code not fixed, closing this pull request. Once you fix your code and get it up to date with develop branch, feel free to reopen it.

2023-12-02 16:11 UTC, closed without merging